# our local base image
FROM ubuntu

# install build dependencies 
RUN apt update
RUN apt install -y build-essential cmake make g++ gcc gdb
RUN apt install -y iproute2 net-tools iputils-ping
# move into a project directory
WORKDIR /home/
RUN mkdir dev
WORKDIR /home/dev